### PR TITLE
Add option to infer msbuild path using vswhere.exe

### PR DESCRIPTION
**Pull request by canpolat**
I'm not a Javascript developer, so this may not be the ideal solution, so, please feel free to take over, if you like. I tried to use the old function that was already in `grunt-msbuild` some time ago and modified it to cover VS2019 (I hope it uses `vswhere` in a more generic way now). We need this due to #47 Hopefully you can take a look soon.

### CODE REVIEW

**Comment by stevewillcock** [comment]
Hi @canpolat, thanks for this! I've been really busy these past few days, I'll take a proper look at this asap and get it merged as soon as I can test it.

Steve

**Comment by canpolat** [comment]
Currently the new flag overrides the msBuildPath variable. Perhaps it may make sense to do it the other way: if `msBuildPath` is set, use it, otherwise, if `inferMsbuildPath` is set, infer the path. Or something like that.

**Comment by stevewillcock** [comment]
Yes, that sounds like it might be a good approach, I’ll take a look, thanks

Steve

**Comment by stevewillcock** [comment]
Hi, all seems to work ok (for my very limited test cases). Published as 1.1.0. I didn't make the change to the msBuildPath variable as you mentioned, seems fine as it is I think. Please let me know if you spot any issues during testing and thanks again!

**Comment by canpolat** [comment]
Thank *you* for quick handling of this PR.

**Pull request merged**
